# Generated by Django 4.2.7 on 2023-11-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('miqdor', models.PositiveIntegerField()),
                ('summa', models.PositiveIntegerField()),
                ('tolangan_summa', models.PositiveIntegerField()),
                ('nasiya', models.IntegerField(blank=True, null=True)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.maxsulot')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mijoz')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.ombor')),
            ],
        ),
    ]
